# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wfenhX2Z6S50noFHKz9H8xubOE6AubeE
"""

import torch
import torch.nn as nn
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
import matplotlib.pyplot as plt
import numpy as np
from torch.utils.data import Dataset, DataLoader, random_split
from torchvision import transforms
from PIL import Image
from pathlib import Path

class AstroDenoisingDataset(Dataset):
    def __init__(self, clean_dir, noisy_dir, transform=None):
        self.clean_paths = sorted(list(Path(clean_dir).glob("*.png")))
        self.noisy_paths = sorted(list(Path(noisy_dir).glob("*.png")))
        assert len(self.clean_paths) == len(self.noisy_paths), "Mismatch between clean and noisy images"
        self.transform = transform or transforms.ToTensor()

    def __len__(self):
        return len(self.clean_paths)

    def __getitem__(self, idx):
        clean_img = Image.open(self.clean_paths[idx]).convert("L")
        noisy_img = Image.open(self.noisy_paths[idx]).convert("L")

        clean_tensor = self.transform(clean_img)
        noisy_tensor = self.transform(noisy_img)

        return noisy_tensor, clean_tensor

import os
import requests
from bs4 import BeautifulSoup
from PIL import Image
from io import BytesIO
from scipy.signal import convolve2d


# Configuration
NUM_IMAGES = 10
OUTPUT_DIR = "Data/astro_simulated_dataset_all"
IMAGE_SIZE = (256, 256)
GAUSSIAN_SIGMA = 0.05
PSF_SIGMA = 2
PSF_SIZE = 11

# Create output directories
clean_dir = Path(OUTPUT_DIR) / "clean"
noisy_dir = Path(OUTPUT_DIR) / "noisy"
clean_dir.mkdir(parents=True, exist_ok=True)
noisy_dir.mkdir(parents=True, exist_ok=True)

# PSF kernel
def gaussian_kernel(size=11, sigma=2):
    ax = np.linspace(-(size // 2), size // 2, size)
    xx, yy = np.meshgrid(ax, ax)
    kernel = np.exp(-(xx**2 + yy**2) / (2. * sigma**2))
    return kernel / np.sum(kernel)

psf = gaussian_kernel(PSF_SIZE, PSF_SIGMA)

# Blur + Noise simulation
def simulate_blurred_noisy(clean_img, psf, sigma):
    blurred = convolve2d(clean_img, psf, mode='same', boundary='wrap')
    noise = np.random.normal(0, sigma, clean_img.shape)
    return np.clip(blurred + noise, 0, 1)

# Save image pair
def process_image(img_bytes, idx):
    try:
        img = Image.open(BytesIO(img_bytes)).convert("L").resize(IMAGE_SIZE)
        clean_np = np.array(img) / 255.0
        noisy_np = simulate_blurred_noisy(clean_np, psf, GAUSSIAN_SIGMA)

        Image.fromarray((clean_np * 255).astype(np.uint8)).save(clean_dir / f"{idx:03d}.png")
        Image.fromarray((noisy_np * 255).astype(np.uint8)).save(noisy_dir / f"{idx:03d}.png")
        return True
    except Exception as e:
        print(f"❌ Failed to process image {idx}: {e}")
        return False

######################
# 1. ESA Top 100
def download_esa_images(n=10):
    base_url = "https://www.spacetelescope.org/images/archive/top100/"
    try:
        soup = BeautifulSoup(requests.get(base_url).text, "html.parser")
        img_tags = soup.select("a[href$='.jpg']")
        urls = ["https://www.spacetelescope.org" + tag["href"] for tag in img_tags][:n]
        return urls
    except Exception as e:
        print(f"❌ ESA scraping error: {e}")
        return []

######################
# 2. NASA Sample Images (predefined known public links)
def download_nasa_images(n=10):
    base_url = "https://hubblesite.org/files/live/sites/hubble/files/home/news/news-releases/"
    example_paths = [
        "2020/2020-16/2020-16a.jpg",
        "2018/2018-17/2018-17a.jpg",
        "2017/2017-04/2017-04a.jpg",
        "2015/2015-12/2015-12a.jpg",
        "2014/2014-24/2014-24a.jpg",
        "2013/2013-37/2013-37a.jpg",
        "2012/2012-37/2012-37a.jpg",
        "2010/2010-13/2010-13a.jpg",
        "2007/2007-16/2007-16a.jpg",
        "2006/2006-01/2006-01a.jpg",
    ]
    return [base_url + path for path in example_paths[:n]]

######################
# 3. SDSS API
def download_sdss_images(n=10):
    return [
        f"https://skyserver.sdss.org/dr16/SkyServerWS/ImgCutout/getjpeg?ra={180+i}&dec=0&scale=0.2&width=256&height=256"
        for i in range(n)
    ]

######################
# Master Downloader
def download_and_process_all():
    sources = [
        ("ESA", download_esa_images),
        ("NASA", download_nasa_images),
        ("SDSS", download_sdss_images),
    ]

    idx = 0
    for label, url_func in sources:
        print(f"\n🔭 Downloading from {label}...")
        urls = url_func(NUM_IMAGES)
        for url in urls:
            try:
                response = requests.get(url, timeout=10)
                if response.status_code == 200:
                    success = process_image(response.content, idx)
                    if success:
                        print(f"✅ [{label}] Image {idx:03d} saved")
                        idx += 1
                else:
                    print(f"❌ [{label}] HTTP {response.status_code} at {url}")
            except Exception as e:
                print(f"❌ [{label}] Error downloading {url}: {e}")

    print(f"\n🎉 Done! {idx} images saved to `{OUTPUT_DIR}`")

######################
# Run it
if __name__ == "__main__":
    download_and_process_all()

clean_dir = "Data/astro_simulated_dataset_all/clean"
noisy_dir = "Data/astro_simulated_dataset_all/noisy"


transform = transforms.Compose([
    transforms.Resize((64, 64)),
    transforms.ToTensor()
])

dataset = AstroDenoisingDataset(clean_dir, noisy_dir, transform=transform)
print(len(dataset))
dataloader = DataLoader(dataset, batch_size=16, shuffle=True)

class DnCNN(nn.Module):
    def __init__(self, channels=1, num_of_layers=17):
        super(DnCNN, self).__init__()
        layers = []
        layers.append(nn.Conv2d(channels, 64, kernel_size=3, padding=1))
        layers.append(nn.ReLU(inplace=True))
        for _ in range(num_of_layers - 2):
            layers.append(nn.Conv2d(64, 64, kernel_size=3, padding=1, bias=False))
            layers.append(nn.BatchNorm2d(64))
            layers.append(nn.ReLU(inplace=True))
        layers.append(nn.Conv2d(64, channels, kernel_size=3, padding=1))
        self.dncnn = nn.Sequential(*layers)

    def forward(self, x):
        out = self.dncnn(x)
        return x - out  # residual learning
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = DnCNN(channels=1).to(device)
criterion = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

num_epochs = 16
for epoch in range(num_epochs):
    model.train()
    running_loss = 0.0

    for noisy_imgs, clean_imgs in dataloader:
        noisy_imgs = noisy_imgs.to(device)
        clean_imgs = clean_imgs.to(device)

        optimizer.zero_grad()
        outputs = model(noisy_imgs)
        loss = criterion(outputs, clean_imgs)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()

    avg_loss = running_loss / len(dataloader)
    print(f"Epoch [{epoch+1}/{num_epochs}], Loss: {avg_loss:.4f}")



model.eval()
with torch.no_grad():
    sample_noisy, sample_clean = next(iter(dataloader))
    sample_noisy = sample_noisy.to(device)
    denoised_output = model(sample_noisy)

# Show a few results
for i in range(5):
    fig, axs = plt.subplots(1, 3, figsize=(9, 3))
    axs[0].imshow(sample_clean[i][0].cpu(), cmap='gray')
    axs[0].set_title("Clean")
    axs[1].imshow(sample_noisy[i][0].cpu(), cmap='gray')
    axs[1].set_title("Noisy")
    axs[2].imshow(denoised_output[i][0].cpu(), cmap='gray')
    axs[2].set_title("Denoised")
    for ax in axs: ax.axis("off")
    plt.tight_layout()
    plt.show()